name: "Lighthouse CI Action"
description: "Audit URLs using Lighthouse and test performance with Lighthouse CI"
inputs:
  urls:
    description: "List of URL(s) to analyze"
  budgetPath:
    description: "Path to a Lighthouse budgets.json file"
  configPath:
    description: "Path to a LHCI lighthouserc.json file"
  uploadArtifacts:
    description: "Opt-out of saving Lighthouse results as an action artifacts"
  artifactName:
    description: "Name of the artifact group if using uploadArtifacts. Default: lighthouse-results"
    default: lighthouse-results
  temporaryPublicStorage:
    description: "Opt-in to saving Lighthouse results to temporary public storage"
  runs:
    description: "Number of runs to do per URL"
  serverBaseUrl:
    description: "Address of a LHCI server"
  serverToken:
    description: "API token to push to LHCI server"
  basicAuthUsername:
    description: "Basic auth username for LHCI server"
  basicAuthPassword:
    description: "Basic auth password for LHCI server"
  gh_token:
    description: "PAT to comment on PR"
  comment_on_pr:
    default: true
    description: "Boolean to define if will comment on PR or not"
  collect_preset:
    description: "Set the collect preset: perf, experimental or desktop. Default: mobile"
  urls_to_compare:
    description: "Which urls should be used to campare results. Useful without config file"
    default: ''
  branch_to_compare:
    description: "Which branch should be used to campare results. Useful for config file. OBS: This parameter is works when urls is NOT defined"
    default: ''
outputs:
  resultsPath:
    description: "Path to the folder with LHCI results"
    value: ${{ steps.treosh-lhci-action.outputs.resultsPath }}
  links:
    description: "Links to compare/result UI for each URL (content of links.json)"
    value: ${{ steps.treosh-lhci-action.outputs.links }}
  assertionResults:
    description: "Assertion results (content of assertion-results.json)"
    value: ${{ steps.treosh-lhci-action.outputs.assertionResults }}
  aggregateResults:
    description: "Json containing all aggregate summary and metrics from runs"
    value: ${{ steps.print.outputs.aggregateResults }}
runs:
  using: "composite"
  steps:
    - name: Set LHCI env vars
      id: set-lhci-env-vars
      shell: bash
      run: |        
        cd ${{github.action_path}}
        source scripts/utils.sh
        _set_up_lhci_env_vars ${{ inputs.collect_preset }}

    - name: Treosh Lighthouse CI Action
      id: treosh-lhci-action
      uses: treosh/lighthouse-ci-action@v9
      with:
        urls: ${{ inputs.urls }}
        budgetPath: ${{ inputs.budgetPath }}
        configPath: ${{ inputs.configPath }}
        uploadArtifacts: ${{ inputs.uploadArtifacts }}
        artifactName: ${{ inputs.artifactName }}
        temporaryPublicStorage: ${{ inputs.temporaryPublicStorage }}
        runs: ${{ inputs.runs }}
        serverBaseUrl: ${{ inputs.serverBaseUrl }}
        serverToken: ${{ inputs.serverToken }}
        basicAuthUsername: ${{ inputs.basicAuthUsername }}
        basicAuthPassword: ${{ inputs.basicAuthPassword }}

    - name: Print outputs
      shell: bash
      id: print
      env:
        COMMENT_ON_PR: ${{ inputs.comment_on_pr }}
        GH_TOKEN: ${{ inputs.gh_token }}
        PR_NUMBER: ${{ github.event.number }}
        RUNS: ${{ inputs.runs }}
        JSON: ${{ steps.treosh-lhci-action.outputs.manifest }}
        LINKS: ${{ steps.treosh-lhci-action.outputs.links }}
        URLS: ${{ inputs.urls }}
      run: |
        ## Print outputs | summary | pr comment
        cd ${{github.action_path}}
        bash scripts/main.sh

    - if: ${{ inputs.urls_to_compare || inputs.branch_to_compare }}
      name: Compare result (When necessary)
      shell: bash
      run: |
        ## Should compare result
        source ${{ github.action_path }}/scripts/utils.sh
        if [ -n '${{ inputs.urls_to_compare }}' ]; then
          _log "Others URLS [${C_GRE}${{ inputs.urls_to_compare }}${C_END}] has been configured to compare results"
        fi

        if [ -n '${{ inputs.branch_to_compare }}' ]; then
          _log "Branch or tag [${C_GRE}${{ inputs.branch_to_compare }}${C_END}] has been configured to compare results"
        fi

    - if: ${{ inputs.branch_to_compare }}
      name: Checkout to specific branch (When necessary)
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch_to_compare }}

    - if: ${{ inputs.urls_to_compare || inputs.branch_to_compare }}
      name: Treosh Lighthouse CI Action (When necessary)
      id: treosh-lhci-action-to-compare
      uses: treosh/lighthouse-ci-action@v9
      with:
        urls: ${{ inputs.urls_to_compare }}
        budgetPath: ${{ inputs.budgetPath }}
        configPath: ${{ inputs.configPath }}
        uploadArtifacts: ${{ inputs.uploadArtifacts }}
        artifactName: ${{ inputs.artifactName }}
        temporaryPublicStorage: ${{ inputs.temporaryPublicStorage }}
        runs: ${{ inputs.runs }}
        serverBaseUrl: ${{ inputs.serverBaseUrl }}
        serverToken: ${{ inputs.serverToken }}
        basicAuthUsername: ${{ inputs.basicAuthUsername }}
        basicAuthPassword: ${{ inputs.basicAuthPassword }}

    - if: success()
      name: Difference between os 2 executions
      shell: bash
      env:
        JSON: ${{ steps.treosh-lhci-action-to-compare.outputs.manifest }}
        URLS: ${{ inputs.urls }}
      run: |
        ## Comparing difference
        echo NEW ${JSON_NEW_RESULTS}
        echo OLD ${JSON_OLD_RESULTS}
        cd ${{github.action_path}}