name: "Lighthouse CI Action"
description: "Audit URLs using Lighthouse and test performance with Lighthouse CI"
inputs:
  urls:
    description: "List of URL(s) to analyze"
  budgetPath:
    description: "Path to a Lighthouse budgets.json file"
  configPath:
    description: "Path to a LHCI lighthouserc.json file"
  uploadArtifacts:
    description: "Opt-out of saving Lighthouse results as an action artifacts"
  artifactName:
    description: "Name of the artifact group if using uploadArtifacts. Default: lighthouse-results"
    default: lighthouse-results
  temporaryPublicStorage:
    description: "Opt-in to saving Lighthouse results to temporary public storage"
  runs:
    description: "Number of runs to do per URL"
  serverBaseUrl:
    description: "Address of a LHCI server"
  serverToken:
    description: "API token to push to LHCI server"
  basicAuthUsername:
    description: "Basic auth username for LHCI server"
  basicAuthPassword:
    description: "Basic auth password for LHCI server"
  gh_token:
    description: "PAT to comment on PR"
  comment_on_pr:
    default: true
    description: "Boolean to define if will comment on PR or not"
  collect_preset:
    description: "Set the collect preset: perf, experimental or desktop. Default: mobile"
    default: ""
  urls_to_compare:
    description: "Which urls should be used to campare results. Useful without config file"
    default: ""
  branch_to_compare:
    description: "Which branch should be used to campare results. Useful for config file."
    default: ""
  puppeteerScript:
    description: "The path to a script that manipulates the browser with puppeteer before running Lighthouse, used for auth."
    default: ""
  puppeteerLaunchOptions:
    description: "The object of puppeteer launch options"
    default: ""
outputs:
  resultsPath:
    description: "Path to the folder with LHCI results"
    value: ${{ steps.treosh-lhci-action.outputs.resultsPath }}
  links:
    description: "Links to compare/result UI for each URL (content of links.json)"
    value: ${{ steps.treosh-lhci-action.outputs.links }}
  assertionResults:
    description: "Assertion results (content of assertion-results.json)"
    value: ${{ steps.treosh-lhci-action.outputs.assertionResults }}
  aggregateResults:
    description: "Json containing all aggregate summary and metrics from runs with diffs results when comparation was used"
    value: ${{ steps.compare-results.outputs.aggregateResults || steps.print.outputs.aggregateResults }}
runs:
  using: "composite"
  steps:
    - name: Check URL availability
      shell: bash
      env:
        ACTIONS_RUNNER_DEBUG: ${{ contains(runner.debug, '1') }}
      run: |
        ## Check if URL is available
        cd ${{github.action_path}}
        source scripts/utils.sh

        ## Remove new line from input
        urls="$(echo '${{ inputs.urls }}' | tr '\n' ' ')"
        urls_to_compare="$(echo '${{ inputs.urls_to_compare }}' | tr '\n' ' ')"
        
        _check_url_availability $urls $urls_to_compare

    - name: Set LHCI env vars
      id: set-lhci-env-vars
      shell: bash
      env:
        ACTIONS_RUNNER_DEBUG: ${{ contains(runner.debug, '1') }}
      run: |
        cd ${{github.action_path}}
        source scripts/utils.sh
        _set_up_lhci_env_vars ${{ inputs.collect_preset }} \
                              ${{ inputs.puppeteerScript }} \
                              ${{ inputs.puppeteerLaunchOptions }}

    - if: ${{ inputs.puppeteerScript }}
      name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - if: ${{ inputs.puppeteerScript }}
      name: Install Puppeteer
      shell: bash
      run: |
        npm install puppeteer
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Treosh Lighthouse CI Action
      id: treosh-lhci-action
      uses: treosh/lighthouse-ci-action@v10
      with:
        urls: ${{ inputs.urls }}
        budgetPath: ${{ inputs.budgetPath }}
        configPath: ${{ inputs.configPath }}
        uploadArtifacts: ${{ inputs.uploadArtifacts }}
        artifactName: ${{ inputs.artifactName }}
        temporaryPublicStorage: ${{ inputs.temporaryPublicStorage }}
        runs: ${{ inputs.runs }}
        serverBaseUrl: ${{ inputs.serverBaseUrl }}
        serverToken: ${{ inputs.serverToken }}
        basicAuthUsername: ${{ inputs.basicAuthUsername }}
        basicAuthPassword: ${{ inputs.basicAuthPassword }}

    - name: Print outputs
      shell: bash
      id: print
      env:
        ACTIONS_RUNNER_DEBUG: ${{ contains(runner.debug, '1') }}
        COMMENT_ON_PR: ${{ inputs.comment_on_pr }}
        GH_TOKEN: ${{ inputs.gh_token }}
        PR_NUMBER: ${{ github.event.number }}
        RUNS: ${{ inputs.runs }}
        JSON: ${{ steps.treosh-lhci-action.outputs.manifest }}
        LINKS: ${{ steps.treosh-lhci-action.outputs.links }}
        URLS: ${{ inputs.urls }}
      run: |
        ## Print outputs and generate report
        cd ${{github.action_path}}
        bash scripts/main.sh

    - if: ${{ inputs.urls_to_compare || inputs.branch_to_compare }}
      name: Compare result (When necessary)
      shell: bash
      env:
        ACTIONS_RUNNER_DEBUG: ${{ contains(runner.debug, '1') }}
      run: |
        ## Should compare result
        source ${{ github.action_path }}/scripts/utils.sh

        ## Trim the string (removes newline)
        URLs="${{ inputs.urls_to_compare }}"
        URLs=$(echo $URLs)

        if [ -n '${{ inputs.urls_to_compare }}' ]; then
          _log "Others URLS [${C_BLU}${URLs}${C_END}] has been configured to compare results"
        fi

        if [ -n '${{ inputs.branch_to_compare }}' ]; then
          _log "Branch or tag [${C_BLU}${{ inputs.branch_to_compare }}${C_END}] has been configured to compare results"
        fi

    - if: ${{ inputs.branch_to_compare }}
      name: Checkout to specific branch (When necessary)
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch_to_compare }}

    - if: ${{ inputs.urls_to_compare || inputs.branch_to_compare }}
      name: Treosh Lighthouse CI Action to compare (When necessary)
      id: treosh-lhci-action-to-compare
      uses: treosh/lighthouse-ci-action@v9
      with:
        urls: ${{ inputs.urls_to_compare }}
        budgetPath: ${{ inputs.budgetPath }}
        configPath: ${{ inputs.configPath }}
        uploadArtifacts: ${{ inputs.uploadArtifacts }}
        artifactName: ${{ inputs.artifactName }}
        temporaryPublicStorage: ${{ inputs.temporaryPublicStorage }}
        runs: ${{ inputs.runs }}
        serverBaseUrl: ${{ inputs.serverBaseUrl }}
        serverToken: ${{ inputs.serverToken }}
        basicAuthUsername: ${{ inputs.basicAuthUsername }}
        basicAuthPassword: ${{ inputs.basicAuthPassword }}

    - if: ${{ steps.treosh-lhci-action-to-compare.conclusion == 'success' }}
      name: Create output for previows version
      id: previous-run
      shell: bash
      env:
        ACTIONS_RUNNER_DEBUG: ${{ contains(runner.debug, '1') }}
        JSON: ${{ steps.treosh-lhci-action-to-compare.outputs.manifest }}
        RUNS: ${{ inputs.runs }}
        URLS: ${{ inputs.urls_to_compare }}
        LINKS: ${{ steps.treosh-lhci-action-to-compare.outputs.links }}
        PREVIOUS_RUN: true
      run: |
        ## Generation previous version outputs
        cd ${{github.action_path}}
        bash scripts/main.sh

    - if: ${{ steps.previous-run.conclusion == 'success' &&
        steps.treosh-lhci-action-to-compare.conclusion == 'success' }}
      name: Difference between os 2 executions
      id: compare-results
      shell: bash
      env:
        ACTIONS_RUNNER_DEBUG: ${{ contains(runner.debug, '1') }}
        JSON: ${{ steps.treosh-lhci-action-to-compare.outputs.manifest }}
        RUNS: ${{ inputs.runs }}
        URLS: ${{ inputs.urls_to_compare }}
        LINKS: ${{ steps.treosh-lhci-action-to-compare.outputs.links }}
        RECENT_RESULTS: ${{ steps.print.outputs.aggregateResults }} ## New Version
        PREVIOUS_RESULTS: ${{ steps.previous-run.outputs.aggregateResults }} ## Old Version
      run: |
        ## Comparing difference
        cd ${{github.action_path}}
        bash scripts/compare_results.sh

    - name: Create Action summary and Comment on PR
      shell: bash
      env:
        ACTIONS_RUNNER_DEBUG: ${{ contains(runner.debug, '1') }}
        COMPARATION_WAS_EXECUTED: ${{ steps.compare-results.conclusion == 'success' }}
        COMMENT_ON_PR: ${{ inputs.comment_on_pr }}
        GH_TOKEN: ${{ inputs.gh_token }}
        PR_NUMBER: ${{ github.event.number }}
      run: |
        ## Writing summary and comment on PR
        cd ${{github.action_path}}
        bash scripts/write_action_summary.sh
        bash scripts/post_pr_comment.sh
